#MongoDB configuration
mongodb_uri: "mongodb://localhost:27017"
mongodb_db: "fact_checker"
mongodb_collection: "embeddings"
mongodb_username: "FC-DB-ADMIN"
mongodb_password: "CHANGE-ME-ADMIN"
mongodb_auth_db: "admin" 

# Model configuration
embeddings_model: "nomic-embed-text-v2-moe"
llm_model: "llama3.2:3B"
ollama_api_endpoint: "http://localhost:11434/api/generate"

# Document loader and chunking configuration
file_path: "./datasets"
chunk_size: 12000
chunk_overlap: 500
